<?php

namespace SysSecurityBundle\Repository;

/**
 * ClientLoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientLoginRepository extends \Doctrine\ORM\EntityRepository
{
}
