<?php

namespace SysSecurityBundle\Repository;

/**
 * LicenceKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenceKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
